name: artifact-buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets?ref=release/1.14.0&depth=1
parameters:
  - name: EncryptionType
    value: SSE
  - name: RetentionType
    value: DESTROY
---
name: tfstate-buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets?ref=release/1.14.0&depth=1
parameters:
  - name: EncryptionType
    value: SSE
  - name: RetentionType
    value: DESTROY
---
name: transfuser-ecr
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/ecr?ref=release/1.13.0&depth=1
targetAccount: primary
parameters:
  - name: ImageTagMutability
    value: MUTABLE
  - name: ImageScanOnPush
    value: True
  - name: Encryption
    value: KMS_MANAGED
  - name: RemovalPolicy
    value: DESTROY