name: transfuser
path: modules/ecr/transfuser-image
targetAccount: primary
parameters:
  - name: EcrRepoName
    valueFrom:
      moduleMetadata:
        group: base
        name: transfuser-ecr
        key: EcrRepositoryName
